/**
 * Generates docs/api/endpoints.md from packages/contracts so the API reference can't drift from code.
 *
 *   npm run docs:api          rewrite the file
 *   npm run docs:api:check    exit 1 if the file is out of date (used by `npm run check`)
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as contracts from "@reel/contracts";
import {
  contractNames,
  endpoints,
  errorHttpStatus,
  errorMeaning,
  type EndpointDefinition,
  type ErrorCode,
  type FeatureId,
} from "@reel/contracts";
import { z } from "zod";

type Json = { [key: string]: any };

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outFile = path.join(root, "docs", "api", "endpoints.md");

const FEATURES: Array<{ id: FeatureId; title: string; doc: string }> = [
  { id: "foundation", title: "F0 Foundation: identity", doc: "F0-foundation.md" },
  { id: "import", title: "F1 Import", doc: "F1-import.md" },
  { id: "places", title: "F2 Place confirmation", doc: "F2-places.md" },
  { id: "trip-setup", title: "F3 Trip setup", doc: "F3-trip-setup.md" },
  { id: "itinerary", title: "F4/F5 Itinerary and views", doc: "F4-itinerary.md" },
  { id: "sharing", title: "F6 Sharing", doc: "F6-sharing.md" },
  { id: "jobs", title: "Jobs", doc: "F1-import.md" },
];

const defs = new Map<string, Json>();

function toTs(schema: z.ZodType, io: "input" | "output"): string {
  const json = z.toJSONSchema(schema, { metadata: contractNames, unrepresentable: "any", io }) as Json;
  for (const [name, def] of Object.entries((json.$defs ?? {}) as Record<string, Json>)) {
    if (!defs.has(name)) defs.set(name, def);
  }
  const id = contractNames.get(schema)?.id;
  if (id && !json.$ref) {
    if (!defs.has(id)) defs.set(id, json);
    return id;
  }
  return print(json, 0);
}

function print(node: Json, depth: number): string {
  if (node.$ref) return decodeURIComponent(String(node.$ref).split("/").pop()!);
  const union = node.anyOf ?? node.oneOf;
  if (union) return (union as Json[]).map((n) => print(n, depth)).join(" | ");
  if (node.allOf) return (node.allOf as Json[]).map((n) => print(n, depth)).join(" & ");
  if (node.enum) return (node.enum as unknown[]).map((v) => JSON.stringify(v)).join(" | ");
  if (node.const !== undefined) return JSON.stringify(node.const);
  if (Array.isArray(node.type)) return node.type.map((t: string) => print({ ...node, type: t }, depth)).join(" | ");

  switch (node.type) {
    case "string":
      return node.format === "binary" || node.contentEncoding === "binary" ? "File" : "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array": {
      const item = node.items ? print(node.items, depth) : "unknown";
      return item.includes(" ") && !item.startsWith("{") ? `Array<${item}>` : `${item}[]`;
    }
    case "object": {
      const props = Object.entries((node.properties ?? {}) as Record<string, Json>);
      if (props.length === 0) return "{}";
      const required = new Set<string>(node.required ?? []);
      const pad = "  ".repeat(depth + 1);
      const lines = props.map(([key, value]) => {
        const comment = value.description && !value.$ref ? ` // ${value.description}` : "";
        return `${pad}${key}${required.has(key) ? "" : "?"}: ${print(value, depth + 1)};${comment}`;
      });
      return `{\n${lines.join("\n")}\n${"  ".repeat(depth)}}`;
    }
    default:
      return "unknown";
  }
}

const anchor = (id: string) => id.toLowerCase().replace(/[^a-z0-9-]/g, "");
const implicitErrors = (def: EndpointDefinition): ErrorCode[] => [
  ...(def.access === "user" ? (["UNAUTHENTICATED"] as const) : []),
  ...(def.params || def.query || def.body ? (["VALIDATION_FAILED"] as const) : []),
];

const entries = Object.entries(endpoints) as Array<[string, EndpointDefinition]>;
const out: string[] = [];

out.push(
  "# API endpoints",
  "",
  "<!-- GENERATED by `npm run docs:api` from packages/contracts/src/api.ts. Do not edit by hand. -->",
  "",
  "This is the contract between the browser and the server. The server router validates every request and",
  "response against these schemas, and the browser client (`apps/web/src/lib/api-client.ts`) is typed from them.",
  "Read the [feature specs](../features/README.md) for screens, states and acceptance checks.",
  "",
  "- Errors always use `{ \"error\": { \"code\", \"message\", \"details\"? } }`. See [error codes](#error-codes).",
  "- `user` endpoints need the session cookie set by `auth.devSignIn`, and may return `UNAUTHENTICATED` (401).",
  "- Endpoints with params, query or a body may return `VALIDATION_FAILED` (400) with `details.issues`.",
  "- `LocalTime` / `LocalDateTime` are wall-clock times in the trip timezone; `Timestamp` is UTC.",
  "",
  "## Index",
  "",
  "| Endpoint | Method and path | Access | UI owner | Server owner |",
  "| --- | --- | --- | --- | --- |",
  ...entries.map(
    ([id, def]) =>
      `| [\`${id}\`](#${anchor(id)}) | \`${def.method} ${def.path}\` | ${def.access} | ${def.owners.ui ?? "–"} | ${def.owners.server} |`,
  ),
  "",
);

for (const feature of FEATURES) {
  const inFeature = entries.filter(([, def]) => def.feature === feature.id);
  if (inFeature.length === 0) continue;
  out.push(`## ${feature.title}`, "", `Spec: [${feature.doc}](../features/${feature.doc})`, "");

  for (const [id, def] of inFeature) {
    out.push(
      `### \`${id}\``,
      "",
      `\`${def.method} ${def.path}\` · access **${def.access}** · UI ${def.owners.ui ?? "none"} · server ${def.owners.server}`,
      "",
      def.summary,
      "",
    );
    if (def.params) out.push("**Path params**", "", "```ts", toTs(def.params, "input"), "```", "");
    if (def.query) out.push("**Query**", "", "```ts", toTs(def.query, "input"), "```", "");
    if (def.body) {
      out.push(`**Body** (${def.bodyKind === "form-data" ? "multipart/form-data" : "JSON"})`, "", "```ts", toTs(def.body, "input"), "```", "");
    }
    out.push(`**Response** \`${def.successStatus ?? 200}\`${def.responseKind === "binary" ? " (binary)" : ""}`, "");
    if (def.responseKind === "binary") {
      out.push("Raw bytes with the stored `Content-Type`.", "");
    } else {
      out.push("```ts", toTs(def.response, "output"), "```", "");
    }
    const errors = [...def.errors, ...implicitErrors(def)];
    out.push(
      `**Errors** ${errors.length ? errors.map((code) => `\`${code}\` (${errorHttpStatus[code]})`).join(", ") : "none"}`,
      "",
    );
  }
}

out.push("## Shared types", "", "Defined in `packages/contracts/src`. Import them from `@reel/contracts`.", "");
const printed = new Set<string>();
while (printed.size < defs.size) {
  for (const [name, def] of [...defs.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    if (printed.has(name)) continue;
    printed.add(name);
    const description = contractNames.get(findSchema(name) ?? z.never())?.description;
    out.push(`### \`${name}\``, "");
    if (description) out.push(description, "");
    out.push("```ts", `type ${name} = ${print(def, 0)};`, "```", "");
  }
}

out.push("## Error codes", "", "| Code | HTTP | Meaning |", "| --- | --- | --- |");
for (const code of Object.keys(errorHttpStatus) as ErrorCode[]) {
  out.push(`| \`${code}\` | ${errorHttpStatus[code]} | ${errorMeaning[code]} |`);
}
out.push("");

function findSchema(name: string): z.ZodType | undefined {
  const exported: unknown[] = Object.values(contracts);
  return exported.find(
    (value): value is z.ZodType => value instanceof z.ZodType && contractNames.get(value)?.id === name,
  );
}

const content = out.join("\n");

if (process.argv.includes("--check")) {
  const current = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== content) {
    console.error("docs/api/endpoints.md is out of date. Run `npm run docs:api` and commit the result.");
    process.exit(1);
  }
  console.log("docs/api/endpoints.md is up to date.");
} else {
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, content);
  console.log(`Wrote ${path.relative(root, outFile)} (${entries.length} endpoints, ${defs.size} shared types).`);
}
